-- ════════════════════════════════════════════════════════════════════════════
-- 360-Immo.ci — données de référence : types de bien, villes, communes, quartiers
--
-- FICHIER GÉNÉRÉ par supabase/references.ts depuis les listes du site
-- (lib/regles-biens.ts, lib/lieux.ts) : ne pas le modifier à la main.
-- 9 types de bien, 188 villes, 201 communes, 119 quartiers.
-- ════════════════════════════════════════════════════════════════════════════

insert into public.types_bien
  (cle, nom, ordre, vendable, meuble, immeuble, pieces, chambres, sanitaires, loyer_par, caution, surface, commodites)
values
  ('appartement', 'Appartement', 1, true, 'option', 'toujours', 'studio', true, 'Salles de bain', array['jour', 'mois', 'annee']::public.unite_loyer[], true, 'Surface', array['Air conditionné', 'Chauffe-eau', 'Balcon', 'Terrasse', 'Jacuzzi', 'Cave', 'Piscine', 'Jardin', 'Garage', 'Parking', 'Ascenseur', 'Gardien', 'Fibre / Wifi', 'Rénové']::text[]),
  ('maison', 'Maison', 2, true, 'option', 'non', 'oui', true, 'Salles de bain', array['jour', 'mois', 'annee']::public.unite_loyer[], true, 'Surface', array['Air conditionné', 'Chauffe-eau', 'Balcon', 'Terrasse', 'Jacuzzi', 'Cave', 'Piscine', 'Jardin', 'Garage', 'Parking', 'Gardien', 'Fibre / Wifi', 'Rénové']::text[]),
  ('villa', 'Villa', 3, true, 'option', 'non', 'oui', true, 'Salles de bain', array['jour', 'mois', 'annee']::public.unite_loyer[], true, 'Surface', array['Air conditionné', 'Chauffe-eau', 'Balcon', 'Terrasse', 'Jacuzzi', 'Cave', 'Piscine', 'Jardin', 'Garage', 'Parking', 'Gardien', 'Fibre / Wifi', 'Rénové']::text[]),
  ('terrain', 'Terrain', 4, true, 'non', 'non', 'non', false, null, array['mois', 'annee']::public.unite_loyer[], true, 'Superficie', array['Terrain clôturé', 'Viabilisé (eau, électricité)', 'Titre foncier (ACD)', 'Accès route bitumée', 'Gardien']::text[]),
  ('bureau', 'Bureau', 5, true, 'option', 'option', 'oui', false, 'Toilettes', array['mois', 'annee']::public.unite_loyer[], true, 'Surface', array['Air conditionné', 'Balcon', 'Terrasse', 'Parking', 'Ascenseur', 'Gardien', 'Fibre / Wifi', 'Rénové']::text[]),
  ('commerce', 'Commerce / Magasin', 6, true, 'non', 'option', 'non', false, 'Toilettes', array['mois', 'annee']::public.unite_loyer[], true, 'Surface', array['Air conditionné', 'Terrasse', 'Parking', 'Gardien', 'Fibre / Wifi', 'Rénové']::text[]),
  ('immeuble', 'Immeuble', 7, true, 'non', 'non', 'non', false, null, array['mois', 'annee']::public.unite_loyer[], true, 'Surface', array['Piscine', 'Jardin', 'Garage', 'Parking', 'Ascenseur', 'Gardien', 'Fibre / Wifi', 'Rénové']::text[]),
  ('hotel', 'Chambre d''hôtel', 8, false, 'toujours', 'non', 'non', false, 'Salles de bain', array['nuit']::public.unite_loyer[], false, 'Surface', array['Air conditionné', 'Chauffe-eau', 'Balcon', 'Terrasse', 'Jacuzzi', 'Piscine', 'Parking', 'Ascenseur', 'Fibre / Wifi']::text[]),
  ('autres', 'Autres', 9, true, 'option', 'option', 'oui', true, 'Salles de bain', array['jour', 'mois', 'annee']::public.unite_loyer[], true, 'Surface', array['Air conditionné', 'Chauffe-eau', 'Balcon', 'Terrasse', 'Jacuzzi', 'Cave', 'Piscine', 'Jardin', 'Garage', 'Parking', 'Ascenseur', 'Gardien', 'Fibre / Wifi', 'Rénové']::text[]);

insert into public.villes (nom) values
  ('Abengourou'),
  ('Abidjan'),
  ('Aboisso'),
  ('Adiaké'),
  ('Adzopé'),
  ('Afféry'),
  ('Agboville'),
  ('Agnibilékrou'),
  ('Agou'),
  ('Akoupé'),
  ('Alépé'),
  ('Anoumaba'),
  ('Arrah'),
  ('Assinie-Mafia'),
  ('Assuéfry'),
  ('Ayamé'),
  ('Azaguié'),
  ('Bako'),
  ('Bangolo'),
  ('Bassawa'),
  ('Bédiala'),
  ('Béoumi'),
  ('Bettié'),
  ('Biankouma'),
  ('Binhouyé'),
  ('Blolequin'),
  ('Bocanda'),
  ('Bodokro'),
  ('Bondoukou'),
  ('Bongouanou'),
  ('Boniérédougou'),
  ('Bonon'),
  ('Bonoua'),
  ('Booko'),
  ('Borotou'),
  ('Botro'),
  ('Bouaflé'),
  ('Bouaké'),
  ('Bouna'),
  ('Boundiali'),
  ('Brobo'),
  ('Buyo'),
  ('Dabakala'),
  ('Dabou'),
  ('Daloa'),
  ('Danané'),
  ('Daoukro'),
  ('Diabo'),
  ('Dianra'),
  ('Diawala'),
  ('Didiévi'),
  ('Diégonéfla'),
  ('Dikodougou'),
  ('Dimbokro'),
  ('Dioulatiédougou'),
  ('Divo'),
  ('Djébonoua'),
  ('Djékanou'),
  ('Djibrosso'),
  ('Doropo'),
  ('Dualla'),
  ('Duékoué'),
  ('Ettrokro'),
  ('Facobly'),
  ('Ferkessédougou'),
  ('Foumbolo'),
  ('Fresco'),
  ('Fronan'),
  ('Gagnoa'),
  ('Gbéléban'),
  ('Gboguhé'),
  ('Gbon'),
  ('Gbonné'),
  ('Gohitafla'),
  ('Goulia'),
  ('Grabo'),
  ('Grand-Bassam'),
  ('Grand-Béréby'),
  ('Grand-Lahou'),
  ('Grand-Zattry'),
  ('Guéyo'),
  ('Guibéroua'),
  ('Guiembé'),
  ('Guiglo'),
  ('Guintéguéla'),
  ('Guitry'),
  ('Hiré'),
  ('Issia'),
  ('Jacqueville'),
  ('Kanakono'),
  ('Kani'),
  ('Kaniasso'),
  ('Karakoro'),
  ('Kasséré'),
  ('Katiola'),
  ('Kokoumbo'),
  ('Kolia'),
  ('Komborodougou'),
  ('Kong'),
  ('Kongasso'),
  ('Koonan'),
  ('Korhogo'),
  ('Koro'),
  ('Kouassi-Datékro'),
  ('Kouassi-Kouassikro'),
  ('Kouibly'),
  ('Koumbala'),
  ('Koun-Fao'),
  ('Kounahiri'),
  ('Kouto'),
  ('Lakota'),
  ('Logoualé'),
  ('M''Bahiakro'),
  ('M''Batto'),
  ('M''Bengué'),
  ('Madinani'),
  ('Maféré'),
  ('Man'),
  ('Mankono'),
  ('Massala'),
  ('Mayo'),
  ('Méagui'),
  ('Minignan'),
  ('Morondo'),
  ('N''Douci'),
  ('Napié'),
  ('Nassian'),
  ('Niablé'),
  ('Niakaramadougou'),
  ('Niellé'),
  ('Niofoin'),
  ('Odienné'),
  ('Ouangolodougou'),
  ('Ouaninou'),
  ('Ouellé'),
  ('Oumé'),
  ('Ouragahio'),
  ('Prikro'),
  ('Rubino'),
  ('Saïoua'),
  ('Sakassou'),
  ('Samatiguila'),
  ('San-Pédro'),
  ('Sandégué'),
  ('Sangouiné'),
  ('Sarhala'),
  ('Sassandra'),
  ('Satama-Sokoro'),
  ('Satama-Sokoura'),
  ('Séguéla'),
  ('Séguélon'),
  ('Seydougou'),
  ('Sifié'),
  ('Sikensi'),
  ('Sinématiali'),
  ('Sinfra'),
  ('Sipilou'),
  ('Sirasso'),
  ('Soubré'),
  ('Taabo'),
  ('Tabou'),
  ('Tafiré'),
  ('Taï'),
  ('Tanda'),
  ('Téhini'),
  ('Tengréla'),
  ('Tiapoum'),
  ('Tiassalé'),
  ('Tié-N''Diékro'),
  ('Tiébissou'),
  ('Tiémé'),
  ('Tiémélékro'),
  ('Tiéningboué'),
  ('Tienko'),
  ('Tioroniaradougou'),
  ('Tortiya'),
  ('Touba'),
  ('Toulépleu'),
  ('Toumodi'),
  ('Transua'),
  ('Vavoua'),
  ('Worofla'),
  ('Yakassé-Attobrou'),
  ('Yamoussoukro'),
  ('Zikisso'),
  ('Zouan-Hounien'),
  ('Zoukougbeu'),
  ('Zuénoula');

insert into public.communes (ville_id, nom)
select v.id, c.commune
from (values
  ('Abengourou', 'Abengourou'),
  ('Abidjan', 'Abobo'),
  ('Abidjan', 'Adjamé'),
  ('Abidjan', 'Anyama'),
  ('Abidjan', 'Attécoubé'),
  ('Abidjan', 'Bingerville'),
  ('Abidjan', 'Cocody'),
  ('Abidjan', 'Koumassi'),
  ('Abidjan', 'Marcory'),
  ('Abidjan', 'Plateau'),
  ('Abidjan', 'Port-Bouët'),
  ('Abidjan', 'Songon'),
  ('Abidjan', 'Treichville'),
  ('Abidjan', 'Yopougon'),
  ('Aboisso', 'Aboisso'),
  ('Adiaké', 'Adiaké'),
  ('Adzopé', 'Adzopé'),
  ('Afféry', 'Afféry'),
  ('Agboville', 'Agboville'),
  ('Agnibilékrou', 'Agnibilékrou'),
  ('Agou', 'Agou'),
  ('Akoupé', 'Akoupé'),
  ('Alépé', 'Alépé'),
  ('Anoumaba', 'Anoumaba'),
  ('Arrah', 'Arrah'),
  ('Assinie-Mafia', 'Assinie-Mafia'),
  ('Assuéfry', 'Assuéfry'),
  ('Ayamé', 'Ayamé'),
  ('Azaguié', 'Azaguié'),
  ('Bako', 'Bako'),
  ('Bangolo', 'Bangolo'),
  ('Bassawa', 'Bassawa'),
  ('Bédiala', 'Bédiala'),
  ('Béoumi', 'Béoumi'),
  ('Bettié', 'Bettié'),
  ('Biankouma', 'Biankouma'),
  ('Binhouyé', 'Binhouyé'),
  ('Blolequin', 'Blolequin'),
  ('Bocanda', 'Bocanda'),
  ('Bodokro', 'Bodokro'),
  ('Bondoukou', 'Bondoukou'),
  ('Bongouanou', 'Bongouanou'),
  ('Boniérédougou', 'Boniérédougou'),
  ('Bonon', 'Bonon'),
  ('Bonoua', 'Bonoua'),
  ('Booko', 'Booko'),
  ('Borotou', 'Borotou'),
  ('Botro', 'Botro'),
  ('Bouaflé', 'Bouaflé'),
  ('Bouaké', 'Bouaké'),
  ('Bouna', 'Bouna'),
  ('Boundiali', 'Boundiali'),
  ('Brobo', 'Brobo'),
  ('Buyo', 'Buyo'),
  ('Dabakala', 'Dabakala'),
  ('Dabou', 'Dabou'),
  ('Daloa', 'Daloa'),
  ('Danané', 'Danané'),
  ('Daoukro', 'Daoukro'),
  ('Diabo', 'Diabo'),
  ('Dianra', 'Dianra'),
  ('Diawala', 'Diawala'),
  ('Didiévi', 'Didiévi'),
  ('Diégonéfla', 'Diégonéfla'),
  ('Dikodougou', 'Dikodougou'),
  ('Dimbokro', 'Dimbokro'),
  ('Dioulatiédougou', 'Dioulatiédougou'),
  ('Divo', 'Divo'),
  ('Djébonoua', 'Djébonoua'),
  ('Djékanou', 'Djékanou'),
  ('Djibrosso', 'Djibrosso'),
  ('Doropo', 'Doropo'),
  ('Dualla', 'Dualla'),
  ('Duékoué', 'Duékoué'),
  ('Ettrokro', 'Ettrokro'),
  ('Facobly', 'Facobly'),
  ('Ferkessédougou', 'Ferkessédougou'),
  ('Foumbolo', 'Foumbolo'),
  ('Fresco', 'Fresco'),
  ('Fronan', 'Fronan'),
  ('Gagnoa', 'Gagnoa'),
  ('Gbéléban', 'Gbéléban'),
  ('Gboguhé', 'Gboguhé'),
  ('Gbon', 'Gbon'),
  ('Gbonné', 'Gbonné'),
  ('Gohitafla', 'Gohitafla'),
  ('Goulia', 'Goulia'),
  ('Grabo', 'Grabo'),
  ('Grand-Bassam', 'Grand-Bassam'),
  ('Grand-Béréby', 'Grand-Béréby'),
  ('Grand-Lahou', 'Grand-Lahou'),
  ('Grand-Zattry', 'Grand-Zattry'),
  ('Guéyo', 'Guéyo'),
  ('Guibéroua', 'Guibéroua'),
  ('Guiembé', 'Guiembé'),
  ('Guiglo', 'Guiglo'),
  ('Guintéguéla', 'Guintéguéla'),
  ('Guitry', 'Guitry'),
  ('Hiré', 'Hiré'),
  ('Issia', 'Issia'),
  ('Jacqueville', 'Jacqueville'),
  ('Kanakono', 'Kanakono'),
  ('Kani', 'Kani'),
  ('Kaniasso', 'Kaniasso'),
  ('Karakoro', 'Karakoro'),
  ('Kasséré', 'Kasséré'),
  ('Katiola', 'Katiola'),
  ('Kokoumbo', 'Kokoumbo'),
  ('Kolia', 'Kolia'),
  ('Komborodougou', 'Komborodougou'),
  ('Kong', 'Kong'),
  ('Kongasso', 'Kongasso'),
  ('Koonan', 'Koonan'),
  ('Korhogo', 'Korhogo'),
  ('Koro', 'Koro'),
  ('Kouassi-Datékro', 'Kouassi-Datékro'),
  ('Kouassi-Kouassikro', 'Kouassi-Kouassikro'),
  ('Kouibly', 'Kouibly'),
  ('Koumbala', 'Koumbala'),
  ('Koun-Fao', 'Koun-Fao'),
  ('Kounahiri', 'Kounahiri'),
  ('Kouto', 'Kouto'),
  ('Lakota', 'Lakota'),
  ('Logoualé', 'Logoualé'),
  ('M''Bahiakro', 'M''Bahiakro'),
  ('M''Batto', 'M''Batto'),
  ('M''Bengué', 'M''Bengué'),
  ('Madinani', 'Madinani'),
  ('Maféré', 'Maféré'),
  ('Man', 'Man'),
  ('Mankono', 'Mankono'),
  ('Massala', 'Massala'),
  ('Mayo', 'Mayo'),
  ('Méagui', 'Méagui'),
  ('Minignan', 'Minignan'),
  ('Morondo', 'Morondo'),
  ('N''Douci', 'N''Douci'),
  ('Napié', 'Napié'),
  ('Nassian', 'Nassian'),
  ('Niablé', 'Niablé'),
  ('Niakaramadougou', 'Niakaramadougou'),
  ('Niellé', 'Niellé'),
  ('Niofoin', 'Niofoin'),
  ('Odienné', 'Odienné'),
  ('Ouangolodougou', 'Ouangolodougou'),
  ('Ouaninou', 'Ouaninou'),
  ('Ouellé', 'Ouellé'),
  ('Oumé', 'Oumé'),
  ('Ouragahio', 'Ouragahio'),
  ('Prikro', 'Prikro'),
  ('Rubino', 'Rubino'),
  ('Saïoua', 'Saïoua'),
  ('Sakassou', 'Sakassou'),
  ('Samatiguila', 'Samatiguila'),
  ('San-Pédro', 'San-Pédro'),
  ('Sandégué', 'Sandégué'),
  ('Sangouiné', 'Sangouiné'),
  ('Sarhala', 'Sarhala'),
  ('Sassandra', 'Sassandra'),
  ('Satama-Sokoro', 'Satama-Sokoro'),
  ('Satama-Sokoura', 'Satama-Sokoura'),
  ('Séguéla', 'Séguéla'),
  ('Séguélon', 'Séguélon'),
  ('Seydougou', 'Seydougou'),
  ('Sifié', 'Sifié'),
  ('Sikensi', 'Sikensi'),
  ('Sinématiali', 'Sinématiali'),
  ('Sinfra', 'Sinfra'),
  ('Sipilou', 'Sipilou'),
  ('Sirasso', 'Sirasso'),
  ('Soubré', 'Soubré'),
  ('Taabo', 'Taabo'),
  ('Tabou', 'Tabou'),
  ('Tafiré', 'Tafiré'),
  ('Taï', 'Taï'),
  ('Tanda', 'Tanda'),
  ('Téhini', 'Téhini'),
  ('Tengréla', 'Tengréla'),
  ('Tiapoum', 'Tiapoum'),
  ('Tiassalé', 'Tiassalé'),
  ('Tié-N''Diékro', 'Tié-N''Diékro'),
  ('Tiébissou', 'Tiébissou'),
  ('Tiémé', 'Tiémé'),
  ('Tiémélékro', 'Tiémélékro'),
  ('Tiéningboué', 'Tiéningboué'),
  ('Tienko', 'Tienko'),
  ('Tioroniaradougou', 'Tioroniaradougou'),
  ('Tortiya', 'Tortiya'),
  ('Touba', 'Touba'),
  ('Toulépleu', 'Toulépleu'),
  ('Toumodi', 'Toumodi'),
  ('Transua', 'Transua'),
  ('Vavoua', 'Vavoua'),
  ('Worofla', 'Worofla'),
  ('Yakassé-Attobrou', 'Yakassé-Attobrou'),
  ('Yamoussoukro', 'Attiégouakro'),
  ('Yamoussoukro', 'Yamoussoukro'),
  ('Zikisso', 'Zikisso'),
  ('Zouan-Hounien', 'Zouan-Hounien'),
  ('Zoukougbeu', 'Zoukougbeu'),
  ('Zuénoula', 'Zuénoula')
) as c (ville, commune)
join public.villes v on v.nom = c.ville;

insert into public.quartiers (commune_id, nom)
select co.id, q.quartier
from (values
  ('Abidjan', 'Abobo', 'Abobo-Gare'),
  ('Abidjan', 'Abobo', 'PK18'),
  ('Abidjan', 'Abobo', 'Anador'),
  ('Abidjan', 'Abobo', 'Avocatier'),
  ('Abidjan', 'Abobo', 'Samaké'),
  ('Abidjan', 'Abobo', 'Sagbé'),
  ('Abidjan', 'Abobo', 'Abobo-Baoulé'),
  ('Abidjan', 'Abobo', 'Akéikoi'),
  ('Abidjan', 'Abobo', 'N''Dotré'),
  ('Abidjan', 'Abobo', 'Kennedy'),
  ('Abidjan', 'Abobo', 'Belleville'),
  ('Abidjan', 'Abobo', 'Biabou'),
  ('Abidjan', 'Adjamé', 'Adjamé-Liberté'),
  ('Abidjan', 'Adjamé', 'Williamsville'),
  ('Abidjan', 'Adjamé', '220 Logements'),
  ('Abidjan', 'Adjamé', 'Bracodi'),
  ('Abidjan', 'Adjamé', 'Paillet'),
  ('Abidjan', 'Adjamé', 'Dallas'),
  ('Abidjan', 'Adjamé', 'Renault'),
  ('Abidjan', 'Adjamé', 'Habitat-Extension'),
  ('Abidjan', 'Adjamé', 'Marie-Thérèse'),
  ('Abidjan', 'Anyama', 'Anyama-Centre'),
  ('Abidjan', 'Anyama', 'Ahouabo'),
  ('Abidjan', 'Anyama', 'Ebimpé'),
  ('Abidjan', 'Anyama', 'Attinguié'),
  ('Abidjan', 'Anyama', 'Akoupé-Zeudji'),
  ('Abidjan', 'Attécoubé', 'Santé'),
  ('Abidjan', 'Attécoubé', 'Locodjro'),
  ('Abidjan', 'Attécoubé', 'Abobo-Doumé'),
  ('Abidjan', 'Attécoubé', 'Agban'),
  ('Abidjan', 'Attécoubé', 'Boribana'),
  ('Abidjan', 'Attécoubé', 'Jérusalem'),
  ('Abidjan', 'Attécoubé', 'Mossikro'),
  ('Abidjan', 'Attécoubé', 'Sebroko'),
  ('Abidjan', 'Attécoubé', 'Cité Fairmont'),
  ('Abidjan', 'Bingerville', 'Bingerville-Centre'),
  ('Abidjan', 'Bingerville', 'Akandjé'),
  ('Abidjan', 'Bingerville', 'Abatta'),
  ('Abidjan', 'Bingerville', 'Eloka'),
  ('Abidjan', 'Bingerville', 'Adjamé-Bingerville'),
  ('Abidjan', 'Bingerville', 'Gbagba'),
  ('Abidjan', 'Bingerville', 'Akouai-Santai'),
  ('Abidjan', 'Cocody', 'Cocody-Centre'),
  ('Abidjan', 'Cocody', 'Deux-Plateaux'),
  ('Abidjan', 'Cocody', 'Vallon'),
  ('Abidjan', 'Cocody', 'Riviera 1'),
  ('Abidjan', 'Cocody', 'Riviera 2'),
  ('Abidjan', 'Cocody', 'Riviera 3'),
  ('Abidjan', 'Cocody', 'Riviera 4'),
  ('Abidjan', 'Cocody', 'Riviera Palmeraie'),
  ('Abidjan', 'Cocody', 'Riviera Golf'),
  ('Abidjan', 'Cocody', 'Angré'),
  ('Abidjan', 'Cocody', 'Blockhaus'),
  ('Abidjan', 'Cocody', 'Danga'),
  ('Abidjan', 'Cocody', 'Ambassades'),
  ('Abidjan', 'Cocody', 'Faya'),
  ('Abidjan', 'Cocody', 'M''Pouto'),
  ('Abidjan', 'Cocody', 'Akouédo'),
  ('Abidjan', 'Cocody', 'Attoban'),
  ('Abidjan', 'Cocody', 'Mermoz'),
  ('Abidjan', 'Cocody', 'Anono'),
  ('Abidjan', 'Koumassi', 'Koumassi-Centre'),
  ('Abidjan', 'Koumassi', 'Remblais'),
  ('Abidjan', 'Koumassi', 'Grand Campement'),
  ('Abidjan', 'Koumassi', 'Sicogi'),
  ('Abidjan', 'Koumassi', 'Prodomo'),
  ('Abidjan', 'Koumassi', 'Soweto'),
  ('Abidjan', 'Koumassi', 'Divo'),
  ('Abidjan', 'Koumassi', 'Zone industrielle'),
  ('Abidjan', 'Marcory', 'Zone 4'),
  ('Abidjan', 'Marcory', 'Biétry'),
  ('Abidjan', 'Marcory', 'Marcory-Résidentiel'),
  ('Abidjan', 'Marcory', 'Anoumabo'),
  ('Abidjan', 'Marcory', 'Sans-Fil'),
  ('Abidjan', 'Marcory', 'Hibiscus'),
  ('Abidjan', 'Marcory', 'Konan Raphaël'),
  ('Abidjan', 'Marcory', 'Champroux'),
  ('Abidjan', 'Marcory', 'Aliodan'),
  ('Abidjan', 'Marcory', 'Remblais'),
  ('Abidjan', 'Plateau', 'Centre des affaires'),
  ('Abidjan', 'Plateau', 'Cité administrative'),
  ('Abidjan', 'Plateau', 'Indénié'),
  ('Abidjan', 'Port-Bouët', 'Vridi'),
  ('Abidjan', 'Port-Bouët', 'Gonzagueville'),
  ('Abidjan', 'Port-Bouët', 'Adjouffou'),
  ('Abidjan', 'Port-Bouët', 'Jean Folly'),
  ('Abidjan', 'Port-Bouët', 'Derrière Wharf'),
  ('Abidjan', 'Port-Bouët', 'Aéroport'),
  ('Abidjan', 'Port-Bouët', 'Anani'),
  ('Abidjan', 'Port-Bouët', 'Petit-Bassam'),
  ('Abidjan', 'Songon', 'Songon-Agban'),
  ('Abidjan', 'Songon', 'Songon-Kassemblé'),
  ('Abidjan', 'Songon', 'Songon-Té'),
  ('Abidjan', 'Songon', 'Songon-M''Brathé'),
  ('Abidjan', 'Songon', 'Songon-Dagbé'),
  ('Abidjan', 'Treichville', 'Arras'),
  ('Abidjan', 'Treichville', 'Biafra'),
  ('Abidjan', 'Treichville', 'Belleville'),
  ('Abidjan', 'Treichville', 'Craonne'),
  ('Abidjan', 'Treichville', 'Gare de Bassam'),
  ('Abidjan', 'Treichville', 'Zone portuaire'),
  ('Abidjan', 'Yopougon', 'Niangon'),
  ('Abidjan', 'Yopougon', 'Selmer'),
  ('Abidjan', 'Yopougon', 'Sideci'),
  ('Abidjan', 'Yopougon', 'Maroc'),
  ('Abidjan', 'Yopougon', 'Toits Rouges'),
  ('Abidjan', 'Yopougon', 'Siporex'),
  ('Abidjan', 'Yopougon', 'Wassakara'),
  ('Abidjan', 'Yopougon', 'Andokoi'),
  ('Abidjan', 'Yopougon', 'Kouté'),
  ('Abidjan', 'Yopougon', 'Port-Bouët 2'),
  ('Abidjan', 'Yopougon', 'Sicogi'),
  ('Abidjan', 'Yopougon', 'Ananeraie'),
  ('Abidjan', 'Yopougon', 'Gesco'),
  ('Abidjan', 'Yopougon', 'Banco'),
  ('Abidjan', 'Yopougon', 'Azito'),
  ('Abidjan', 'Yopougon', 'Millionnaire'),
  ('Abidjan', 'Yopougon', 'Mamie Adjoua'),
  ('Abidjan', 'Yopougon', 'Ficgayo')
) as q (ville, commune, quartier)
join public.villes v on v.nom = q.ville
join public.communes co on co.ville_id = v.id and co.nom = q.commune;
